<?php if (get_field('facebook', 'options')){ ?><a href="<?php the_field('facebook', 'options');?>"><span class="fa fa-facebook-square"></span></a><?php } ?>
<?php if (get_field('twitter', 'options')){ ?><a href="<?php the_field('twitter', 'options');?>"><span class="fa fa-twitter-square"></span></a><?php } ?>
<?php if (get_field('google_plus', 'options')){ ?><a href="<?php the_field('google_plus', 'options');?>"><span class="fa fa-google-plus-square"></span></a><?php } ?>
<?php if (get_field('linkedin', 'options')){ ?><a href="<?php the_field('linkedin', 'options');?>"><span class="fa fa-linkedin-square"></span></a><?php } ?>
<?php if (get_field('instagram', 'options')){ ?><a href="<?php the_field('instagram', 'options');?>"><span class="fa fa-instagram"></span></a><?php } ?>
<?php if (get_field('flickr', 'options')){ ?><a href="<?php the_field('flickr', 'options');?>"><span class="fa fa-flickr-square"></span></a><?php } ?>
<?php if (get_field('youtube', 'options')){ ?><a href="<?php the_field('youtube', 'options');?>"><span class="fa fa-youtube-square"></span></a><?php } ?>
<?php if (get_field('tumblr', 'options')){ ?><a href="<?php the_field('tumblr', 'options');?>"><span class="fa fa-tumblr-square"></span></a><?php } ?>
<?php if (get_field('pinterest', 'options')){ ?><a href="<?php the_field('pinterest', 'options');?>"><span class="fa fa-pinterest-square"></span></a><?php } ?>